# Counting DNA Nucleotides +

# import timeit

# a = timeit.default_timer()

dnaString = 'GAACCCAAGTCCGTTTTCAGGACTACTCTACCGATGTGCTTCCGTTATTGCTTGCAGTCAAGCTGTAGCTGCTGATGTACCTGCGGCCAAGCTCGCGCAAGGAATCTGAACGCGCCCCTCAAAATAGAGAGGTTCTGCAGCTTGCACCTACATTGTTGCTGCCGAAAGTACGTAGACATAGGACAGACACGTGACGAGTCCCGTATCTGAAGGTAATCGTTACATAGTCTCATTACGTGCATTTGGTCTAAAGGTAGTCTACAAGAAATGGGAAACCCTTGTAATTTACCTCTTAAAGTGGCTAGTTCCCTACAATACAATTGCGTGGCTTAGACGAAATGAGGTCGCTGCCTTACGTACCGTAAGGACGTTCGTTCGCGCCAGCCTACCTAGGTAGGCTGCTGAATGCTTCCTTGCAGGAGCTTACAGAGCGGCAGGGACCGAACAAAAACCACCTAAAGATTTTGATTGGGCCAACAGGTCATAGCTGAGATGTGCAGAAGCCCGGCGTTTCTCTCCTGTGGGGTTTAGTCATCGGGGACTAAGAAGGACACTTCTTCGAAGTTTAGACGTGGACAATGAGTCATGCGATAAAAACTTATGATCTTCACGCAGGCTCGGCGATACCTGTAGGCCACCATACACCATCATCATCCGACTGAGATGCCGTAGGCCAGGACTGATGTTTCGTAAAAATGGAACTCAAGATCGCTCTTGCTCTCCAGAACGATAATCCCGCCTTTGACCGATGCCGCCTCCTCTAACTGGTCGGCGCCTCGTCGTTTAAACGGTCCATCTAAAGCACGTAGTTTCTGGGTTATATCATCTTCGAACAGCCAATCGGATGATGCGGAAGATAGTAGCCCTCGCTCAACCGGCACGACCGCGAAATGACGCGCGCTCCACATTGGGCAAGTTGGATCTACAAATAGCTATTGCTTATGCCTAA'

# first variant
result = {}

for element in dnaString:
  if element in result:
    result[element] = result[element] + 1
  else:
    result[element] = 1

for key in sorted(result):
  print(result[key], end=' ')


# second variant
# A_cnt = 0
# T_cnt = 0
# G_cnt = 0
# C_cnt = 0
# i = 0
# lengthDnaString = len(dnaString)

# while i < lengthDnaString:
#   if dnaString[i] == 'A':
#     A_cnt = A_cnt + 1
#   if dnaString[i] == 'T':
#     T_cnt = T_cnt + 1
#   if dnaString[i] == 'G':
#     G_cnt = G_cnt + 1
#   if dnaString[i] == 'C':
#     C_cnt = C_cnt + 1
#   i = i + 1


# print(timeit.default_timer()-a)  